In [1]:
sentence = """Thomas Jefferson began building Monticello at the age of 26."""

sentence.split()

['Thomas',
 'Jefferson',
 'began',
 'building',
 'Monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [2]:
str.split(sentence)

['Thomas',
 'Jefferson',
 'began',
 'building',
 'Monticello',
 'at',
 'the',
 'age',
 'of',
 '26.']

In [3]:
import numpy as np

token_sequence = str.split(sentence)
vocab = sorted(set(token_sequence))

print('token sequence: ', ', '.join(vocab))
print()

num_tokens = len(token_sequence)
vocab_size = len(vocab)
onehot_vectors = np.zeros((num_tokens, vocab_size), int)

for i,word in enumerate(token_sequence):
    onehot_vectors[i, vocab.index(word)] = 1

print('vocab: ', ' '.join(vocab))
print()
print('onehot vectors: \n', onehot_vectors)

token sequence:  26., Jefferson, Monticello, Thomas, age, at, began, building, of, the

vocab:  26. Jefferson Monticello Thomas age at began building of the

onehot vectors: 
 [[0 0 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [4]:
import pandas as pd

pd.DataFrame(onehot_vectors, columns=vocab)

26.  Jefferson  Monticello  Thomas  age  at  began  building  of  the
0    0          0           0       1    0   0      0         0   0    0
1    0          1           0       0    0   0      0         0   0    0
2    0          0           0       0    0   0      1         0   0    0
3    0          0           0       0    0   0      0         1   0    0
4    0          0           1       0    0   0      0         0   0    0
5    0          0           0       0    0   1      0         0   0    0
6    0          0           0       0    0   0      0         0   0    1
7    0          0           0       0    1   0      0         0   0    0
8    0          0           0       0    0   0      0         0   1    0
9    1          0           0       0    0   0      0         0   0    0

In [5]:
df = pd.DataFrame(onehot_vectors, columns=vocab)
df[df == 0] = ''
df

26. Jefferson Monticello Thomas age at began building of the
0                               1                             
1             1                                               
2                                            1                
3                                                     1       
4                        1                                    
5                                      1                      
6                                                            1
7                                   1                         
8                                                        1    
9   1

In [6]:
num_rows = 3000 * 3500 * 15
num_rows

157500000

In [7]:
num_bytes = num_rows * 1000000
num_bytes

157500000000000

In [8]:
num_bytes / 1e9

157500.0

In [9]:
_ / 1000

157.5

In [10]:
sentence_bow = {}

for token in sentence.split():
    sentence_bow[token] = 1
    
sorted(sentence_bow.items())

[('26.', 1),
 ('Jefferson', 1),
 ('Monticello', 1),
 ('Thomas', 1),
 ('age', 1),
 ('at', 1),
 ('began', 1),
 ('building', 1),
 ('of', 1),
 ('the', 1)]

In [24]:
df = pd.DataFrame(pd.Series(dict([(token, 1) for token in sentence.split()])), columns=['sent']).T
df

Thomas  Jefferson  began  building  Monticello  at  the  age  of  26.
sent       1          1      1         1           1   1    1    1   1    1

In [12]:
sentences = """Thomas Jefferson began building Monticello at the age of 26.\n"""
sentences += """Construction was done mostly by local masons and carpenters.\n"""
sentences += """He moved into the South Pavilion in 1770.\n"""
sentences += """Turning Monticello into a neoclassical masterpiece was Jefferson's obsession."""

In [13]:
corpus = {}

for i, sent in enumerate(sentences.split('\n')):
    corpus['sent{}'.format(i)] = dict((tok, 1) for tok in sent.split())
    
df = pd.DataFrame.from_records(corpus).fillna(0).astype(int)
df[df.columns[:10]]

sent0  sent1  sent2  sent3
Thomas            1      0      0      0
Jefferson         1      0      0      0
began             1      0      0      0
building          1      0      0      0
Monticello        1      0      0      1
at                1      0      0      0
the               1      0      1      0
age               1      0      0      0
of                1      0      0      0
26.               1      0      0      0
Construction      0      1      0      0
was               0      1      0      1
done              0      1      0      0
mostly            0      1      0      0
by                0      1      0      0
local             0      1      0      0
masons            0      1      0      0
and               0      1      0      0
carpenters.       0      1      0      0
He                0      0      1      0
moved             0      0      1      0
into              0      0      1      1
South             0      0      1      0
Pavilion          0      0      1      0
in                0      0      1      0
1770.             0      0      1      0
Turning           0      0      0      1
a                 0      0      0      1
neoclassical      0      0      0      1
masterpiece       0      0      0      1
Jefferson's       0      0      0      1
obsession.        0      0      0      1