In [1]:
import numpy as np

mat0 = np.array([[0,1,0],[1,2,1],[0,1,0]])
mat1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("mat0: \n", mat0)
print()
print("mat1: \n", mat1)
print()

sum = 0

for i in range(3):
    for j in range(3):
        sum += mat0[i,j] * mat1[i,j]

print("sum: \n", sum)
print()

mat_mul = mat0 * mat1
print("mat_mul: \n", mat_mul)
print()

mat_mul = np.multiply(mat0,mat1)
print("mat_mul \n", mat_mul)
print()
print("mat_mul.sum: \n", mat_mul.sum())

mat0: 
 [[0 1 0]
 [1 2 1]
 [0 1 0]]

mat1: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

sum: 
 30

mat_mul: 
 [[ 0  2  0]
 [ 4 10  6]
 [ 0  8  0]]

mat_mul 
 [[ 0  2  0]
 [ 4 10  6]
 [ 0  8  0]]

mat_mul.sum: 
 30


In [3]:
import cv2 as cv

def filter_gray(img, kernel):
    kh, kw = kernel.shape[0:2]
    kh2, kw2 = kh//2, kw//2

    tmp_shape = list(img.shape)
    tmp_shape[0] += kh2*2
    tmp_shape[1] += kw2*2

    tmp = np.zeros(tmp_shape, img.dtype)

    np.copyto(tmp[kh2:kh2+img.shape[0], kw2:kw2+img.shape[1]], img)
    
    cv.imshow('tmp', tmp)

    dst = np.zeros(img.shape, img.dtype)

    for i in range(dst.shape[0]):
        for j in range(dst.shape[1]):
            dst[i,j] = (tmp[i:i+kh, j:j+kw] * kernel).sum()

    return dst

img = cv.imread('filter_blur.jpg', cv.IMREAD_GRAYSCALE)

ksize = 9

kernel = np.full((ksize,ksize), 1./(ksize*ksize))

img_filtered = filter_gray(img, kernel)

cv.imshow('original', img)
cv.imshow('filtered', img_filtered)
cv.waitKey()
cv.destroyAllWindows()

In [4]:
def filter_gray(img, kernel):
    kh, kw = kernel.shape[0:2]
    kh2, kw2 = kh//2, kw//2

    tmp_shape = list(img.shape)
    tmp_shape[0] += kh2*2
    tmp_shape[1] += kw2*2

    tmp = np.zeros(tmp_shape, img.dtype)

    np.copyto(tmp[kh2:kh2+img.shape[0], kw2:kw2+img.shape[1]], img)
    
    cv.imshow('tmp', tmp)

    dst = np.zeros(img.shape, img.dtype)

    for i in range(dst.shape[0]):
        for j in range(dst.shape[1]):
            dst[i,j] = (tmp[i:i+kh, j:j+kw] * kernel).sum()

    return dst

def filter_color(img, kernel):
    channels = list(cv.split(img))
    channels_filtered = []

    for channel in channels:
        channels_filtered.append(filter_gray(channel, kernel))
    
    return cv.merge(channels_filtered)

img = cv.imread('filter_blur.jpg', cv.IMREAD_COLOR)

ksize = 9
kernel = np.full((ksize,ksize), 1./(ksize*ksize))

img_filtered = filter_color(img, kernel)

cv.imshow('original', img)
cv.imshow('filtered', img_filtered)
cv.waitKey()
cv.destroyAllWindows()