numpy

In [4]:
import numpy as np

x = np.array(([1,2,3], [4,5,6]))
print("x:\n", x)

x:
 [[1 2 3]
 [4 5 6]]


scipy

In [5]:
from scipy import sparse

eye = np.eye(4)
print("Numpy 배열:\n", eye)

Numpy 배열:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
sparse_matrix = sparse.csr_matrix(eye)
print("\nScipy의 CSR 행렬:\n", sparse_matrix)


Scipy의 CSR 행렬:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [8]:
data = np.ones(4)
row_indices = np.arange(4)
col_indices = np.arange(4)
eye_coo = sparse.coo_matrix((data, (row_indices, col_indices)))
print("COO 표현:\n", eye_coo)

COO 표현:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


matplotlib