In [1]:
import pandas as pd
import warnings

warnings.filterwarnings(action='ignore')

In [2]:
complaints_data = pd.read_csv("Consumer_Complaints.csv", sep=",")
complaints_data.head()

Date received                  Product                  Sub-product  \
0    07/29/2013            Consumer Loan                 Vehicle loan   
1    07/29/2013  Bank account or service             Checking account   
2    07/29/2013  Bank account or service             Checking account   
3    07/29/2013  Bank account or service             Checking account   
4    07/29/2013                 Mortgage  Conventional fixed mortgage   

                                      Issue Sub-issue  \
0                Managing the loan or lease       NaN   
1                 Using a debit or ATM card       NaN   
2   Account opening, closing, or management       NaN   
3                  Deposits and withdrawals       NaN   
4  Loan servicing, payments, escrow account       NaN   

  Consumer complaint narrative Company public response  \
0                          NaN                     NaN   
1                          NaN                     NaN   
2                          NaN                     NaN   
3                          NaN                     NaN   
4                          NaN                     NaN   

                      Company State ZIP code            Tags  \
0       Wells Fargo & Company    VA    24540             NaN   
1       Wells Fargo & Company    CA    95992  Older American   
2           Santander Bank US    NY    10065             NaN   
3       Wells Fargo & Company    GA    30084             NaN   
4  Franklin Credit Management    CT    06106             NaN   

  Consumer consent provided? Submitted via Date sent to company  \
0                        NaN         Phone           07/30/2013   
1                        NaN           Web           07/31/2013   
2                        NaN           Fax           07/31/2013   
3                        NaN           Web           07/30/2013   
4                        NaN           Web           07/30/2013   

  Company response to consumer Timely response? Consumer disputed?  \
0      Closed with explanation              Yes                 No   
1      Closed with explanation              Yes                 No   
2                       Closed              Yes                 No   
3      Closed with explanation              Yes                 No   
4      Closed with explanation              Yes                 No   

   Complaint ID  
0        468882  
1        468889  
2        468879  
3        468949  
4        475823

In [3]:
complaints_data.shape

(670598, 18)

In [4]:
complaints_data.columns

Index(['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue',
       'Consumer complaint narrative', 'Company public response', 'Company',
       'State', 'ZIP code', 'Tags', 'Consumer consent provided?',
       'Submitted via', 'Date sent to company', 'Company response to consumer',
       'Timely response?', 'Consumer disputed?', 'Complaint ID'],
      dtype='object')

In [5]:
data = complaints_data[['Product','Sub-product', 'Issue', 'Company', 'State', 'Submitted via']]

In [6]:
data

Product                             Sub-product  \
0                 Consumer Loan                            Vehicle loan   
1       Bank account or service                        Checking account   
2       Bank account or service                        Checking account   
3       Bank account or service                        Checking account   
4                      Mortgage             Conventional fixed mortgage   
...                         ...                                     ...   
670593         Credit reporting                                     NaN   
670594                 Mortgage  Conventional adjustable mortgage (ARM)   
670595         Credit reporting                                     NaN   
670596              Credit card                                     NaN   
670597            Consumer Loan                        Installment loan   

                                           Issue                     Company  \
0                     Managing the loan or lease       Wells Fargo & Company   
1                      Using a debit or ATM card       Wells Fargo & Company   
2        Account opening, closing, or management           Santander Bank US   
3                       Deposits and withdrawals       Wells Fargo & Company   
4       Loan servicing, payments, escrow account  Franklin Credit Management   
...                                          ...                         ...   
670593    Incorrect information on credit report                     Equifax   
670594  Loan modification,collection,foreclosure                    Citibank   
670595    Incorrect information on credit report                     Equifax   
670596                Closing/Cancelling account                        Amex   
670597                Managing the loan or lease           BancorpSouth Bank   

       State Submitted via  
0         VA         Phone  
1         CA           Web  
2         NY           Fax  
3         GA           Web  
4         CT           Web  
...      ...           ...  
670593    NV           Web  
670594    UT           Web  
670595    TN           Web  
670596    FL           Web  
670597    MS           Web  

[670598 rows x 6 columns]

In [7]:
data02 = data.dropna(how="any")

In [8]:
data02

Product                             Sub-product  \
0                 Consumer Loan                            Vehicle loan   
1       Bank account or service                        Checking account   
2       Bank account or service                        Checking account   
3       Bank account or service                        Checking account   
4                      Mortgage             Conventional fixed mortgage   
...                         ...                                     ...   
670587          Debt collection   Other (i.e. phone, health club, etc.)   
670589          Debt collection   Other (i.e. phone, health club, etc.)   
670592                 Mortgage                          Other mortgage   
670594                 Mortgage  Conventional adjustable mortgage (ARM)   
670597            Consumer Loan                        Installment loan   

                                           Issue                     Company  \
0                     Managing the loan or lease       Wells Fargo & Company   
1                      Using a debit or ATM card       Wells Fargo & Company   
2        Account opening, closing, or management           Santander Bank US   
3                       Deposits and withdrawals       Wells Fargo & Company   
4       Loan servicing, payments, escrow account  Franklin Credit Management   
...                                          ...                         ...   
670587                     Communication tactics            Gross Polowy LLC   
670589     Cont'd attempts collect debt not owed     Transworld Systems Inc.   
670592  Loan modification,collection,foreclosure       Wells Fargo & Company   
670594  Loan modification,collection,foreclosure                    Citibank   
670597                Managing the loan or lease           BancorpSouth Bank   

       State Submitted via  
0         VA         Phone  
1         CA           Web  
2         NY           Fax  
3         GA           Web  
4         CT           Web  
...      ...           ...  
670587    NY   Postal mail  
670589    MO           Web  
670592    WA      Referral  
670594    UT           Web  
670597    MS           Web  

[468289 rows x 6 columns]

In [9]:
data02.shape

(468289, 6)

In [10]:
print(data02['Product'].value_counts())
print()
print(data02['Sub-product'].value_counts())
print()
print(data02['Issue'].value_counts())
print()
print(data02['Company'].value_counts())
print()
print(data02['State'].value_counts())
print()
print(data02['Submitted via'].value_counts())

Mortgage                   208905
Debt collection            123488
Bank account or service     74707
Consumer Loan               26444
Student loan                21504
Payday loan                  4765
Money transfers              4540
Prepaid card                 3135
Other financial service       788
Virtual currency               13
Name: Product, dtype: int64

Other mortgage                            80710
Conventional fixed mortgage               64842
Checking account                          52184
Other (i.e. phone, health club, etc.)     36923
I do not know                             25858
Credit card                               24988
Conventional adjustable mortgage (ARM)    23551
FHA mortgage                              22252
Non-federal student loan                  20558
Medical                                   17066
Vehicle loan                              15023
Other bank product/service                14280
Payday loan                               11400
Home eq

#### complains!!  
* Product:       Mortgage  
* Sub-product:   Other mortgage  
* Issue:         Loan modification,collection,foreclosure  
* Company:       Bank of America  
* State:         CA (California)  
* Submitted via: Web  

### Y = <span style="color:brown">'Submitted Via'</span>

In [11]:
data03 = pd.DataFrame(columns=['Product','Sub-product', 'Issue', 'Company', 'State', 'Submitted via'])

In [12]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data03['Product'] = le.fit_transform(data02['Product'])
data03['Sub-product'] = le.fit_transform(data02['Sub-product'])
data03['Issue'] = le.fit_transform(data02['Issue'])
data03['Company'] = le.fit_transform(data02['Company'])
data03['State'] = le.fit_transform(data02['State'])
data03['Submitted via'] = le.fit_transform(data02['Submitted via'])

In [13]:
data03

Product  Sub-product  Issue  Company  State  Submitted via
0             1           46     38     3808     55              2
1             0            4     57     3808      8              5
2             0            4      0     3182     42              1
3             0            4     17     3808     15              5
4             4            6     33     1514     10              5
...         ...          ...    ...      ...    ...            ...
468284        2           29     12     1670     42              3
468285        2           29     13     3598     31              5
468286        4           31     32     3808     58              4
468287        4            5     32      810     54              5
468288        1           22     38      480     33              5

[468289 rows x 6 columns]

In [14]:
X  = data03[['Product','Sub-product', 'Issue', 'Company', 'State']].values 

In [15]:
X[:10]

array([[   1,   46,   38, 3808,   55],
       [   0,    4,   57, 3808,    8],
       [   0,    4,    0, 3182,   42],
       [   0,    4,   17, 3808,   15],
       [   4,    6,   33, 1514,   10],
       [   0,    4,   17,  481,   53],
       [   2,   29,   13, 2453,   55],
       [   2,   20,   13, 3414,   13],
       [   4,   31,   33, 3808,   41],
       [   4,   31,   32,  481,   35]])

In [16]:
Y = data03['Submitted via'].values

In [17]:
Y[:10]

array([2, 5, 1, 5, 5, 5, 5, 4, 4, 4])

In [18]:
from sklearn import preprocessing

X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [19]:
X[:10]

array([[-0.97648739,  2.08986615,  0.88235619,  1.49063904,  1.525281  ],
       [-1.49553494, -1.21317037,  2.23025046,  1.49063904, -1.19613138],
       [-1.49553494, -1.21317037, -1.81343235,  0.96894175,  0.77254992],
       [-1.49553494, -1.21317037, -0.60742169,  1.49063904, -0.79081464],
       [ 0.58065528, -1.05588292,  0.52764717, -0.42113984, -1.08032659],
       [-1.49553494, -1.21317037, -0.60742169, -1.28202371,  1.40947622],
       [-0.45743983,  0.7529228 , -0.8911889 ,  0.36140609,  1.525281  ],
       [-0.45743983,  0.04512926, -0.8911889 ,  1.16228643, -0.90661942],
       [ 0.58065528,  0.91021025,  0.52764717,  1.49063904,  0.71464753],
       [ 0.58065528,  0.91021025,  0.45670537, -1.28202371,  0.36723318]])

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

In [21]:
X_train.shape

(327802, 5)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

train_acc = []
test_acc = []

for n in range(1,21):
    clf = KNeighborsClassifier(n_jobs=-1, n_neighbors=n)
    clf.fit(X_train, Y_train)
    prediction = clf.predict(X_test)
    train_acc.append(clf.score(X_train, Y_train))
    test_acc.append((prediction==Y_test).mean())
    
plt.figure(figsize=(12, 9))
plt.plot(range(1, 21), train_acc, label='TRAIN set')
plt.plot(range(1, 21), test_acc, label='TEST set')
plt.xlabel("n_neighbors")
plt.ylabel("accuracy")
plt.xticks(np.arange(0, 21, step=1))
plt.legend()

![Accuracy](Accuracy.png)

It seems like test accuracy continuously increase if K increases.

#### KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier

k = 20
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [24]:
from sklearn import metrics

print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.7415116442242573
accuracy score of test:  0.7302810936243211

recall score of train:  0.7415116442242573
recall score of test:  0.7302810936243211

precision score of train:  0.7415116442242573
precision score of test:  0.7302810936243211

confusion_matrix of train:  [[     0      0      2      3     80     76]
 [     0    275     40     90   2527   1949]
 [     0      6    984     39   3773  21760]
 [     0     67    127   1037   7087   7134]
 [     0    294    550    672  44583  23682]
 [     0     51    833    154  13737 196190]]
confusion_matrix of test:  [[    0     0     1     1    49    29]
 [    0   112    19    34  1037   786]
 [    0     1   309    18  1757  9477]
 [    0    27    49   393  3144  3073]
 [    0   134   258   321 18433 10724]
 [    0    13   451    64  6425 83348]]


#### LDA

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [26]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.6032513529508667
accuracy score of test:  0.6192886174521486

recall score of train:  0.6032513529508667
recall score of test:  0.6192886174521486

precision score of train:  0.6032513529508667
precision score of test:  0.6192886174521486

confusion_matrix of train:  [[     0      0      0      0      5    156]
 [     0      0      0      0     79   4802]
 [     0      0      0      0    758  25804]
 [     0      0      0      0    284  15168]
 [     0      0      0      0   1072  68709]
 [     0      0      0      0  14290 196675]]
confusion_matrix of test:  [[    0     0     0     0     5    75]
 [    0     0     0     0    62  1926]
 [    0     0     0     0   536 11026]
 [    0     0     0     0   221  6465]
 [    0     0     0     0   634 29236]
 [    0     0     0     0  3933 86368]]


#### LogisticRegression

In [27]:
from sklearn.linear_model import LogisticRegression

linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [28]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.6197157032323275


Opinion:  
Focusing mainly on KNN and LDA, KNN seems much better when letting Y as 'Submitted via' in my analysis.  
Plus, when I search loglinear, logistic regression pops up. So, I add the score of that method briefly.  
By the way, It seems hard to find optimal K at KNN technique!

### Y = <span style="color:brown">'State'</span>

In [29]:
X  = data03[['Product','Sub-product', 'Issue', 'Company', 'Submitted via']].values
Y = data03['State'].values

In [30]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(int))

In [31]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

![Accuracy](Accuracy02.png)

#### KNN

In [32]:
k = 100
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [33]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.17880000732149284
accuracy score of test:  0.1658516446361585

recall score of train:  0.17880000732149284
recall score of test:  0.1658516446361585

precision score of train:  0.17880000732149284
precision score of test:  0.1658516446361585

confusion_matrix of train:  [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 50  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
confusion_matrix of test:  [[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


#### LDA

In [34]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [35]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.15268058157058223
accuracy score of test:  0.1513947909771011

recall score of train:  0.15268058157058223
recall score of test:  0.1513947909771011

precision score of train:  0.15268058157058223
precision score of test:  0.1513947909771011

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LogisticRegression

In [36]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [37]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

accuracy score of test:  0.1513947909771011


Opinion:  
I think that comparing performance is not that useful in my analysis because of the low score.  
It seems like if numbers of Y increase, the performance dramatically decreases.  
'Submiitted Via' has 6, but 'State' has 62.  
I guess that 'Company, 'Issue' and 'Product' will also have similar performance.  
Anyway, I will continue the test.

### Y = <span style="color:brown">'Company'</span>

In [38]:
X  = data03[['Product','Sub-product', 'Issue', 'State', 'Submitted via']].values
Y = data03['Company'].values

In [39]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [40]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [41]:
k = 100
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [42]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.1854808695493011
accuracy score of test:  0.1734466534270075

recall score of train:  0.1854808695493011
recall score of test:  0.1734466534270075

precision score of train:  0.1854808695493011
precision score of test:  0.1734466534270075

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LDA

In [43]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [44]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.07246752612857761
accuracy score of test:  0.12617537565753414

recall score of train:  0.07246752612857761
recall score of test:  0.12617537565753414

precision score of train:  0.07246752612857761
precision score of test:  0.12617537565753414

confusion_matrix of train:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
confusion_matrix of test:  [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### LogisticRegression

It seems like using too much RAM..  
I think this is not that useful. If someone runs the code below, maybe It will run forever. 

In [ ]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

In [ ]:
print('accuracy score of test: ', linear.score(X_test, Y_test))

Opinion:  
Too low performance to compare..  
Plus linear model is down because of too much load on RAM.  
As I said above, it is not that good for my analysis to compare.   

### Y = <span style="color:brown">'Issue'</span>

In [46]:
X  = data03[['Product','Sub-product','Company', 'State', 'Submitted via']].values
Y = data03['Issue'].values

In [47]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [48]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [51]:
k = 120
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [52]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.4886943947870971
accuracy score of test:  0.4806281008207165

recall score of train:  0.4886943947870971
recall score of test:  0.4806281008207165

precision score of train:  0.4886943947870971
precision score of test:  0.4806281008207165

confusion_matrix of train:  [[19748     0     0 ...     0     0     0]
 [  146    25     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [ 2785     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
confusion_matrix of test:  [[8336    0    0 ...    0    0    0]
 [  63   10    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [1172    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


#### LDA

In [53]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [54]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.07703735791727934
accuracy score of test:  0.4551809064183875

recall score of train:  0.07703735791727934
recall score of test:  0.4551809064183875

precision score of train:  0.07703735791727934
precision score of test:  0.4551809064183875

confusion_matrix of train:  [[11012     0     0 ...     0     0     0]
 [  326     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [ 1673     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
confusion_matrix of test:  [[9060    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [1460    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]


#### LogisticRegression

In [55]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [56]:
print('accuracy score of test: ',    linear.score(X_test, Y_test))

accuracy score of test:  0.4528461708200759


Opinion:  
Interesting..  
KNN looks slightly better than LDA.  
Little bit low, but I think my guess is wrong that I mention above..

### Y = <span style="color:brown">'Product'</span>

In [57]:
X  = data03[['Sub-product','Issue', 'Company', 'State', 'Submitted via']].values
Y = data03['Product'].values

In [58]:
X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))

In [59]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)

#### KNN

In [62]:
k = 35
my_model = KNeighborsClassifier(n_neighbors=k).fit(X_train, Y_train)
Ypredict = my_model.predict(X_test)

In [63]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, my_model.predict(X_train)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, Ypredict))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, my_model.predict(X_train), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, Ypredict, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, my_model.predict(X_train), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, Ypredict, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, my_model.predict(X_train)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, Ypredict))

accuracy score of train:  0.9426544072336349
accuracy score of test:  0.9395602440083424

recall score of train:  0.9426544072336349
recall score of test:  0.9395602440083424

precision score of train:  0.9426544072336349
precision score of test:  0.9395602440083424

confusion_matrix of train:  [[ 48668    146   1422      2   1716      0     22      1    258      0]
 [   388  16948    191    107    764      0     87     13     60      0]
 [  1720    419  83203    224    360      1    160     61    434      0]
 [   114    340    608   2007     76      0      0      3      1      0]
 [  1183    625   2103      7 141748      0    110      8    345      0]
 [   174     12    268     25     54      0      1      8     14      0]
 [     2     26    536      0    202      0   2552      0      3      0]
 [    78    214    706     42    334      0     19    810     32      0]
 [    37      8   1536      5    375      0      0      0  13068      0]
 [     0      0      1      7      0      0    

#### LDA

In [64]:
lda = LDA()
X_train02 = lda.fit_transform(X_train, Y_train)
X_test02 = lda.transform(X_test)
y_predicted_test = lda.predict(X_test) 

In [65]:
print('accuracy score of train: ',   metrics.accuracy_score(Y_train, lda.predict(X_train02)))
print('accuracy score of test: ',    metrics.accuracy_score(Y_test, y_predicted_test))
print()
print('recall score of train: ',     metrics.recall_score(Y_train, lda.predict(X_train02), average='micro'))
print('recall score of test: ',      metrics.recall_score(Y_test, y_predicted_test, average='micro'))
print()
print('precision score of train: ',  metrics.precision_score(Y_train, lda.predict(X_train02), average='micro'))
print('precision score of test: ',   metrics.precision_score(Y_test, y_predicted_test, average='micro'))
print()
print('confusion_matrix of train: ', metrics.confusion_matrix(Y_train, lda.predict(X_train02)))
print('confusion_matrix of test: ',  metrics.confusion_matrix(Y_test, y_predicted_test))

accuracy score of train:  0.5464396190383219
accuracy score of test:  0.676838426331262

recall score of train:  0.5464396190383219
recall score of test:  0.676838426331262

precision score of train:  0.5464396190383219
precision score of test:  0.676838426331262

confusion_matrix of train:  [[ 20490   4079   4740      0  22926      0      0      0      0      0]
 [   257   6690   7120      0   3415      0   1076      0      0      0]
 [ 14662   5197  41063      0  25660      0      0      0      0      0]
 [     0    204    323      0   2622      0      0      0      0      0]
 [  9285   3222  22728      0 110881      0     13      0      0      0]
 [    15     59    110      0    372      0      0      0      0      0]
 [   387    388   2456      0     90      0      0      0      0      0]
 [   151    733    361      0    990      0      0      0      0      0]
 [  1981   3653   7695      0   1700      0      0      0      0      0]
 [     0      0      0      0      8      0      0

#### LogisticRegression

In [66]:
linear = LogisticRegression()
linear.fit(X_train, Y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [67]:
print('accuracy score of test: ',    linear.score(X_test, Y_test))

accuracy score of test:  0.6741549040124709


Opinion:  
Wow, Surprised!!!!  
This seems interesting...  
Anyway, KNN seems much better than LDA.