In [ ]:
# 피드포워드 뉴럴네트워크 계산 예시 (1)
import torch

x = torch.tensor([2,1])
w1 = torch.tensor([[3,2,-4],[2,-3,1]])
b1 = 1
w2 = torch.tensor([[-1, 1], [1,2], [3,1]])
b2 = -1

In [ ]:
# 피드포워드 뉴럴네트워크 계산 예시 (2)
h_preact = torch.matmul(x, w1) + b1
h = torch.nn.functional.relu(h_preact)
y = torch.matmul(h, w2) + b2

In [ ]:
 h_preact

tensor([ 9,  2, -6])

In [ ]:
h

tensor([9, 2, 0])

In [ ]:
y

tensor([-8, 12])

In [ ]:
# 레이어 정규화 예시
input = torch.tensor([[1.0, 2.0, 3.0], [1.0, 1.0, 1.0]])
m = torch.nn.LayerNorm(input.shape[-1])
output = m(input)

In [ ]:
output

tensor([[-1.2247,  0.0000,  1.2247],
        [ 0.0000,  0.0000,  0.0000]], grad_fn=<NativeLayerNormBackward0>)

In [ ]:
m.weight

Parameter containing:
tensor([1., 1., 1.], requires_grad=True)

In [ ]:
m.bias

Parameter containing:
tensor([0., 0., 0.], requires_grad=True)

In [ ]:
# 드롭아웃
m = torch.nn.Dropout(p=0.2)
input = torch.randn(1, 10)
output = m(input)

In [ ]:
input

tensor([[ 2.0720,  1.0007,  1.6847, -0.5129, -1.5362,  0.2534,  0.0181, -1.6540,
         -0.8076,  1.1447]])

In [ ]:
output

tensor([[ 2.5900,  1.2509,  2.1059, -0.6411, -0.0000,  0.3168,  0.0226, -2.0675,
         -1.0095,  1.4308]])

In [ ]:
# # 아담 옵티마이저
# from torch.optim import Adam

# optimizer = Adam(model.parameters(), lr=model.learning_rate)