In [1]:
import cv2 as cv
import numpy as np

In [2]:
mat0 = np.uint8([[130,140], [150,160]])
mat1 = np.uint8([[100,100], [100,100]])
mat2 = np.uint8([[145,145], [145,145]])

In [3]:
mat0, mat1, mat2

(array([[130, 140],
        [150, 160]], dtype=uint8),
 array([[100, 100],
        [100, 100]], dtype=uint8),
 array([[145, 145],
        [145, 145]], dtype=uint8))

In [4]:
mat0 + mat1

array([[230, 240],
       [250,   4]], dtype=uint8)

In [5]:
cv.add(mat0, mat1)

array([[230, 240],
       [250, 255]], dtype=uint8)

In [6]:
mat0 - mat2

array([[241, 251],
       [  5,  15]], dtype=uint8)

In [7]:
cv.subtract(mat0, mat2)

array([[ 0,  0],
       [ 5, 15]], dtype=uint8)

In [8]:
cv.addWeighted(mat0, 0.7, mat1, 0.3, 1)

array([[122, 129],
       [136, 143]], dtype=uint8)