1.5 연습문제

In [1]:
# 1.
import torch

a = torch.rand(3,3)
a.unsqueeze(0)

tensor([[[0.4739, 0.0391, 0.0470],
         [0.2864, 0.6121, 0.4118],
         [0.7225, 0.0479, 0.2685]]])

In [2]:
# 2.
a.squeeze(0)

tensor([[0.4739, 0.0391, 0.0470],
        [0.2864, 0.6121, 0.4118],
        [0.7225, 0.0479, 0.2685]])

In [3]:
# 3.
3 + torch.rand(5,3) * (7 - 3)

tensor([[3.3865, 3.9854, 4.0172],
        [5.6274, 6.6140, 4.6298],
        [6.3609, 4.3075, 6.3066],
        [3.6090, 6.2999, 3.6859],
        [3.0501, 4.7150, 5.9337]])

In [4]:
# 4.
a = torch.rand(3,3)
a.normal_()

tensor([[ 0.5740, -1.0429, -1.4335],
        [-0.8971,  0.0998, -2.4692],
        [ 0.8825,  0.2892, -1.6896]])

In [5]:
# 5.
a = torch.Tensor([1,1,1,0,1])
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

In [6]:
# 6.
a = torch.rand(3,1)
a.expand(3,4)

tensor([[0.1786, 0.1786, 0.1786, 0.1786],
        [0.1231, 0.1231, 0.1231, 0.1231],
        [0.1496, 0.1496, 0.1496, 0.1496]])

In [7]:
# 7.
a = torch.rand(3,4,5)
b = torch.rand(3,5,4)
torch.bmm(a,b)

tensor([[[1.0770, 1.5270, 1.5314, 1.2361],
         [1.2145, 1.5297, 1.2219, 1.2236],
         [1.4142, 2.0833, 1.5695, 1.5547],
         [1.9385, 2.2871, 1.9094, 1.9185]],

        [[1.2646, 1.3253, 1.3798, 1.4798],
         [1.2540, 1.2484, 1.4219, 1.5584],
         [1.4521, 1.4089, 1.3735, 1.5900],
         [1.1309, 1.3479, 1.1051, 1.3873]],

        [[1.7158, 1.3899, 0.6456, 1.7242],
         [1.5631, 1.4670, 0.6993, 1.8436],
         [1.2543, 0.8897, 0.3306, 0.8398],
         [1.2289, 0.9101, 0.4963, 1.4752]]])

In [8]:
# 8.
a = torch.rand(3,4,5)
b = torch.rand(5,4)
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[1.1458, 0.7423, 0.8487, 0.9926],
         [1.8744, 1.4132, 1.1931, 1.6688],
         [1.2676, 1.0110, 1.1172, 1.4127],
         [1.8298, 1.0770, 1.6513, 1.7615]],

        [[1.9016, 1.2229, 1.5348, 1.7132],
         [1.7202, 0.9258, 1.4189, 1.4147],
         [1.2037, 0.8857, 0.7153, 0.9378],
         [2.1269, 1.5949, 1.2925, 1.8104]],

        [[0.8565, 0.9903, 0.2989, 0.8421],
         [1.7182, 1.1574, 1.1981, 1.4287],
         [1.5118, 0.9975, 1.0843, 1.2453],
         [0.8142, 0.5374, 0.5436, 0.6453]]])