In [ ]:
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier, GradientBoostingClassifier

In [ ]:
import pandas as pd
from sklearn.metrics import classification_report
import numpy as np
import warnings

warnings.filterwarnings('ignore')
np.random.seed(1234)

dataset = pd.read_excel('/content/drive/MyDrive/dataset_final_exam.xlsx')

In [ ]:
dataset.isnull().sum()

(in1)        0
(in2)        0
(in3)        1
(in4)        0
(in5)        0
(in6)        0
(in7)        0
(in8)        0
(in9)        0
(in10)       0
(in11)       0
(in12)       0
(in13)       0
(in14)       0
(in15)     174
(in16)     203
(in17)       1
(in18)       1
(in19)       1
(in20)       1
(in21)       1
(in22)     176
(Label)     40
dtype: int64

In [ ]:
dataset['(in1)'] = dataset['(in1)'].replace(['F','M'],[0,1])
dataset['(in1)'] = dataset['(in1)'].replace(['F ',' F'],[0,0])
dataset['(in15)'] = dataset['(in15)'].fillna(130) #15에서 값이 점진적으로 상향되고 있는 마지막 값이 130이다
dataset['(in16)'] = dataset['(in16)'].fillna(0) #Variation이 있지만 데이터 보면 0이 많은 것으로 보아 0으로 채움
dataset['(in22)'] = dataset['(in22)'].fillna(value = dataset['(in22)'].mean()) #규칙찾기가 어려워 보편적인 평균값을 채워 넣음
dataset['(in21)'] = dataset['(in21)'].fillna(value = dataset['(in21)'].mean()) #규칙찾기가 어려워 보편적인 평균값을 채워 넣음
dataset[['(in17)', '(in18)', '(in19)', '(in20)']] = dataset[['(in17)', '(in18)', '(in19)', '(in20)']].fillna(0)#17,18,19,20는 대부분 5단위로 되어 있어 평균값은 이 5단위로 나오지 않을 가능성이 있어서 0으로 채움
dataset['(in3)'] = dataset['(in3)'].fillna(0) #0 또는 1이어서 임의로 정함 
dataset[['(in14)', '(in21)']] = dataset[['(in14)', '(in21)']].round(decimals=1)
dataset[['(in2) ', '(in3)', '(in4)', '(in5)', '(in6)', '(in7)', '(in8)',
       '(in9)', '(in10)', '(in11)', '(in12)', '(in13)', '(in15)',
       '(in16)', '(in17)', '(in18)', '(in19)', '(in20)', '(in22)']] = dataset[['(in2) ', '(in3)', '(in4)', '(in5)', '(in6)', '(in7)', '(in8)',
                                                                               '(in9)', '(in10)', '(in11)', '(in12)', '(in13)', '(in15)',
                                                                               '(in16)', '(in17)', '(in18)', '(in19)', '(in20)', '(in22)']].astype(int)

In [ ]:
new_train_data = pd.DataFrame(data=dataset.iloc[:760])
new_test_data = pd.DataFrame(data=dataset.iloc[760:])

In [ ]:
X = new_train_data[['(in1)', '(in2) ', '(in3)', '(in4)', '(in5)', '(in6)', '(in7)', '(in8)',
       '(in9)', '(in10)', '(in11)', '(in12)', '(in13)', '(in14)', '(in15)',
       '(in16)', '(in17)', '(in18)', '(in19)', '(in20)', '(in21)', '(in22)']]
Y = new_train_data['(Label)']

In [ ]:
test_X = new_test_data[['(in1)', '(in2) ', '(in3)', '(in4)', '(in5)', '(in6)', '(in7)', '(in8)', '(in9)', '(in10)',
                    '(in11)', '(in12)', '(in13)', '(in14)', '(in15)', '(in16)', '(in17)', '(in18)', '(in19)', '(in20)', '(in21)', '(in22)']]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.2)



---



In [ ]:
LR = LogisticRegression()
model01 = LR.fit(X_train, y_train)

In [ ]:
prediction = model01.predict(X_test)
print(accuracy_score(y_test, prediction))
print(classification_report(y_test, prediction))

0.6842105263157895
              precision    recall  f1-score   support

         0.0       0.65      0.46      0.54        61
         1.0       0.70      0.84      0.76        91

    accuracy                           0.68       152
   macro avg       0.67      0.65      0.65       152
weighted avg       0.68      0.68      0.67       152



In [ ]:
real_prediction = model01.predict(test_X)
real_prediction

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 0., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0.])



---



In [ ]:
decision_tree = DecisionTreeClassifier()
model02 = decision_tree.fit(X_train, y_train)

In [ ]:
prediction02 = decision_tree.predict(X_test)
print(accuracy_score(y_test, prediction02))
print(classification_report(y_test, prediction02))

0.7105263157894737
              precision    recall  f1-score   support

         0.0       0.65      0.59      0.62        61
         1.0       0.74      0.79      0.77        91

    accuracy                           0.71       152
   macro avg       0.70      0.69      0.69       152
weighted avg       0.71      0.71      0.71       152



In [ ]:
real_prediction02 = model02.predict(test_X)
real_prediction02

array([1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 1.])



---



In [ ]:
SVM = SVC(probability = True)
model03 = SVM.fit(X_train, y_train)

In [ ]:
prediction03 = model03.predict(X_test)
print(accuracy_score(y_test, prediction03))
print(classification_report(y_test, prediction03))

0.743421052631579
              precision    recall  f1-score   support

         0.0       0.81      0.48      0.60        61
         1.0       0.72      0.92      0.81        91

    accuracy                           0.74       152
   macro avg       0.76      0.70      0.70       152
weighted avg       0.76      0.74      0.73       152



In [ ]:
real_prediction03 = model03.predict(test_X)
real_prediction03

array([1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0.])



---



In [ ]:
# from sklearn.model_selection import GridSearchCV

# params ={
#     'n_estimators':[100,200],
#     'max_depth':[6,8,10,12],
#     'min_samples_leaf':[3,5,7,8,10,12,18],
#     'min_samples_split':[2,3,5,10,8,16,20]
# }

In [ ]:
# rf = RandomForestClassifier(random_state=0, n_jobs=-1)
# grid_cv = GridSearchCV(rf, param_grid=params, cv=2, n_jobs=-1)
# grid_cv.fit(X_train,y_train)

In [ ]:
# print("최고점수: {0:.3f}".format(grid_cv.best_score_))
# print("최고점수:", grid_cv.best_params_)

In [ ]:
random_forest = RandomForestClassifier()
model04 = random_forest.fit(X_train, y_train)

In [ ]:
model04

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
prediction04 = model04.predict(X_test)
print(accuracy_score(y_test, prediction04))
print(classification_report(y_test, prediction04))

0.7960526315789473
              precision    recall  f1-score   support

         0.0       0.84      0.61      0.70        61
         1.0       0.78      0.92      0.84        91

    accuracy                           0.80       152
   macro avg       0.81      0.76      0.77       152
weighted avg       0.80      0.80      0.79       152



In [ ]:
real_prediction04 = model04.predict(test_X)
real_prediction04

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 0.])



---



In [ ]:
KNN = KNeighborsClassifier()
model05 = KNN.fit(X_train, y_train)

In [ ]:
prediction05 = model05.predict(X_test)
print(accuracy_score(y_test, prediction05))
print(classification_report(y_test, prediction05))

0.7171052631578947
              precision    recall  f1-score   support

         0.0       0.70      0.52      0.60        61
         1.0       0.73      0.85      0.78        91

    accuracy                           0.72       152
   macro avg       0.71      0.69      0.69       152
weighted avg       0.71      0.72      0.71       152



In [ ]:
real_prediction05 = model05.predict(test_X)
real_prediction05

array([1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 0., 1., 0., 0.])



---



In [ ]:
bayes = GaussianNB()
model06 = bayes.fit(X_train, y_train)

In [ ]:
prediction06 = model06.predict(X_test)
print(accuracy_score(y_test, prediction06))
print(classification_report(y_test, prediction06))

0.6578947368421053
              precision    recall  f1-score   support

         0.0       0.55      0.75      0.64        61
         1.0       0.78      0.59      0.68        91

    accuracy                           0.66       152
   macro avg       0.67      0.67      0.66       152
weighted avg       0.69      0.66      0.66       152



In [ ]:
real_prediction06 = model06.predict(test_X)
real_prediction06

array([0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1.,
       1., 0., 1., 1., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0.])



---



In [ ]:
models = [LogisticRegression(),
         DecisionTreeClassifier(),
         SVC(probability = True),
         LinearDiscriminantAnalysis(),
         QuadraticDiscriminantAnalysis(),
         RandomForestClassifier(),
         KNeighborsClassifier(),
         GaussianNB()]

In [ ]:
models_ens = list(zip(['LR', 'DT', 'SVM', 'LDA', 'QDA', 'RF', 'KNN', 'NB'], models))

model_ens01 = VotingClassifier(estimators = models_ens, voting = 'hard')
model_ens01.fit(X_train, y_train)
prediction07 = model_ens01.predict(X_test)

print(accuracy_score(y_test, prediction07))
print(classification_report(y_test, prediction07))

0.7697368421052632
              precision    recall  f1-score   support

         0.0       0.75      0.64      0.69        61
         1.0       0.78      0.86      0.82        91

    accuracy                           0.77       152
   macro avg       0.77      0.75      0.75       152
weighted avg       0.77      0.77      0.77       152



In [ ]:
real_prediction07 = model_ens01.predict(test_X)
real_prediction07

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 0., 0.])



---



In [ ]:
model_ens02 = VotingClassifier(estimators = models_ens, voting = 'soft')
model_ens02.fit(X_train, y_train)
prediction08 = model_ens02.predict(X_test)
prob = model_ens02.predict_proba(X_test)[:,1]

print(accuracy_score(y_test, prediction08))
print(classification_report(y_test, prediction08))

0.7368421052631579
              precision    recall  f1-score   support

         0.0       0.70      0.61      0.65        61
         1.0       0.76      0.82      0.79        91

    accuracy                           0.74       152
   macro avg       0.73      0.72      0.72       152
weighted avg       0.73      0.74      0.73       152



In [ ]:
real_prediction08 = model_ens02.predict(test_X)
real_prediction08

array([1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0.])



---



In [ ]:
QDA = QuadraticDiscriminantAnalysis()
model07 = QDA.fit(X_train, y_train)

In [ ]:
prediction09 = model07.predict(X_test)
print(accuracy_score(y_test, prediction09))
print(classification_report(y_test, prediction09))

0.625
              precision    recall  f1-score   support

         0.0       0.52      0.84      0.64        61
         1.0       0.81      0.48      0.61        91

    accuracy                           0.62       152
   macro avg       0.67      0.66      0.62       152
weighted avg       0.70      0.62      0.62       152



In [ ]:
real_prediction09 = model07.predict(test_X)
real_prediction09

array([0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0.,
       1., 1., 1., 1., 1., 1.])



---



In [ ]:
!pip install xgboost

In [ ]:
model08 = SVC(kernel='rbf', probability=True)
model08.fit(X_train, y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
prediction10 = model08.predict(X_test)
print(accuracy_score(y_test, prediction10))
print(classification_report(y_test, prediction10))

0.743421052631579
              precision    recall  f1-score   support

         0.0       0.81      0.48      0.60        61
         1.0       0.72      0.92      0.81        91

    accuracy                           0.74       152
   macro avg       0.76      0.70      0.70       152
weighted avg       0.76      0.74      0.73       152



In [ ]:
real_prediction10 = model08.predict(test_X)
real_prediction10

array([1., 1., 1., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 0.])



---



In [ ]:
from xgboost import XGBClassifier

model09 = XGBClassifier(
    max_depth=2,
    gamma=2,
    eta=0.8,
    reg_alpha=0.5,
    reg_lambda=0.5
)

model09.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eta=0.8, gamma=2,
              learning_rate=0.1, max_delta_step=0, max_depth=2,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0.5, reg_lambda=0.5, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
prediction11 = model09.predict(X_test)
print(accuracy_score(y_test, prediction11))
print(classification_report(y_test, prediction11))

0.743421052631579
              precision    recall  f1-score   support

         0.0       0.71      0.61      0.65        61
         1.0       0.76      0.84      0.80        91

    accuracy                           0.74       152
   macro avg       0.74      0.72      0.73       152
weighted avg       0.74      0.74      0.74       152



In [ ]:
real_prediction11 = model09.predict(test_X)
real_prediction11

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0.])



---



In [ ]:
from sklearn.feature_selection import RFE

model10 = RFE(XGBClassifier(n_jobs=-1, random_state=1))

model10.fit(X_train, y_train)

RFE(estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                            colsample_bylevel=1, colsample_bynode=1,
                            colsample_bytree=1, gamma=0, learning_rate=0.1,
                            max_delta_step=0, max_depth=3, min_child_weight=1,
                            missing=None, n_estimators=100, n_jobs=-1,
                            nthread=None, objective='binary:logistic',
                            random_state=1, reg_alpha=0, reg_lambda=1,
                            scale_pos_weight=1, seed=None, silent=None,
                            subsample=1, verbosity=1),
    n_features_to_select=None, step=1, verbose=0)

In [ ]:
prediction12 = model10.predict(X_test)
print(accuracy_score(y_test, prediction12))
print(classification_report(y_test, prediction12))

0.7368421052631579
              precision    recall  f1-score   support

         0.0       0.69      0.62      0.66        61
         1.0       0.76      0.81      0.79        91

    accuracy                           0.74       152
   macro avg       0.73      0.72      0.72       152
weighted avg       0.73      0.74      0.73       152



In [ ]:
real_prediction12 = model10.predict(test_X)
real_prediction12

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 0., 0., 1., 1., 0.])



---



In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
y = new_train_data['(Label)'].values
x = new_train_data.drop(['(Label)'], axis=1)
x = x.values

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x, y,test_size=0.2,random_state=1234)

In [ ]:
model = tf.keras.Sequential([tf.keras.layers.Dense(units=128, activation='relu', input_shape=(22,)),
                             tf.keras.layers.Dense(units=128, activation='relu'),
                             tf.keras.layers.Dense(units=1, activation='sigmoid')])

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               2944      
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 129       
Total params: 19,585
Trainable params: 19,585
Non-trainable params: 0
_________________________________________________________________


In [ ]:
history = model.fit(x_train, y_train, epochs=25, batch_size=16, validation_split=0.2,
                    callbacks=[tf.keras.callbacks.EarlyStopping(patience=3, monitor='val_loss')])

Epoch 1/25
31/31 [==============================] - 2s 17ms/step - loss: 1.5888 - accuracy: 0.5678 - val_loss: 1.1886 - val_accuracy: 0.5984
Epoch 2/25
31/31 [==============================] - 0s 4ms/step - loss: 0.8600 - accuracy: 0.6975 - val_loss: 0.8126 - val_accuracy: 0.7049
Epoch 3/25
31/31 [==============================] - 0s 4ms/step - loss: 0.7409 - accuracy: 0.7019 - val_loss: 0.7952 - val_accuracy: 0.7049
Epoch 4/25
31/31 [==============================] - 0s 4ms/step - loss: 0.8084 - accuracy: 0.6422 - val_loss: 0.9596 - val_accuracy: 0.6557
Epoch 5/25
31/31 [==============================] - 0s 4ms/step - loss: 0.7492 - accuracy: 0.7180 - val_loss: 1.0768 - val_accuracy: 0.6475
Epoch 6/25
31/31 [==============================] - 0s 4ms/step - loss: 0.5979 - accuracy: 0.7372 - val_loss: 0.7675 - val_accuracy: 0.7131
Epoch 7/25
31/31 [==============================] - 0s 4ms/step - loss: 0.6119 - accuracy: 0.7448 - val_loss: 0.7664 - val_accuracy: 0.7049
Epoch 8/25
31/31 [=

In [ ]:
model.evaluate(x_test, y_test)

5/5 [==============================] - 0s 3ms/step - loss: 0.7608 - accuracy: 0.6974


[0.7608118057250977, 0.6973684430122375]

In [ ]:
pred = model.predict(test_X.values)

In [ ]:
pred.astype(int)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0]])



---



In [ ]:
model11 = GradientBoostingClassifier()

model11.fit(X_train, y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [ ]:
prediction13 = model11.predict(X_test)
print(accuracy_score(y_test, prediction13))
print(classification_report(y_test, prediction13))

0.743421052631579
              precision    recall  f1-score   support

         0.0       0.71      0.61      0.65        61
         1.0       0.76      0.84      0.80        91

    accuracy                           0.74       152
   macro avg       0.74      0.72      0.73       152
weighted avg       0.74      0.74      0.74       152



In [ ]:
real_prediction13 = model11.predict(test_X)
real_prediction13

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1., 0.,
       0., 1., 0., 0., 0., 1.])



---



In [ ]:
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier

model12 = HistGradientBoostingClassifier()

model12.fit(X_train, y_train)

HistGradientBoostingClassifier(l2_regularization=0.0, learning_rate=0.1,
                               loss='auto', max_bins=255, max_depth=None,
                               max_iter=100, max_leaf_nodes=31,
                               min_samples_leaf=20, n_iter_no_change=None,
                               random_state=None, scoring=None, tol=1e-07,
                               validation_fraction=0.1, verbose=0,
                               warm_start=False)

In [ ]:
prediction14 = model12.predict(X_test)
print(accuracy_score(y_test, prediction14))
print(classification_report(y_test, prediction14))

0.756578947368421
              precision    recall  f1-score   support

         0.0       0.71      0.67      0.69        61
         1.0       0.79      0.81      0.80        91

    accuracy                           0.76       152
   macro avg       0.75      0.74      0.74       152
weighted avg       0.75      0.76      0.76       152



In [ ]:
real_prediction14 = model12.predict(test_X)
real_prediction14

array([0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1.,
       0., 1., 0., 1., 1., 0.])



---



In [ ]:
from sklearn.ensemble import ExtraTreesClassifier

model14 = ExtraTreesClassifier()

model14.fit(X_train, y_train)

ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='auto',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_impurity_split=None,
                     min_samples_leaf=1, min_samples_split=2,
                     min_weight_fraction_leaf=0.0, n_estimators=100,
                     n_jobs=None, oob_score=False, random_state=None, verbose=0,
                     warm_start=False)

In [ ]:
prediction16 = model14.predict(X_test)
print(accuracy_score(y_test, prediction16))
print(classification_report(y_test, prediction16))

0.7302631578947368
              precision    recall  f1-score   support

         0.0       0.73      0.52      0.61        61
         1.0       0.73      0.87      0.79        91

    accuracy                           0.73       152
   macro avg       0.73      0.70      0.70       152
weighted avg       0.73      0.73      0.72       152



In [ ]:
real_prediction16 = model14.predict(test_X)
real_prediction16

array([1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 1., 1.])



---



In [ ]:
from sklearn.neural_network import MLPClassifier

model15 = MLPClassifier()

model15.fit(X_train, y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(100,), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=None, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [ ]:
prediction17 = model15.predict(X_test)
print(accuracy_score(y_test, prediction17))
print(classification_report(y_test, prediction17))

0.6447368421052632
              precision    recall  f1-score   support

         0.0       0.55      0.67      0.60        61
         1.0       0.74      0.63      0.68        91

    accuracy                           0.64       152
   macro avg       0.64      0.65      0.64       152
weighted avg       0.66      0.64      0.65       152



In [ ]:
real_prediction17 = model15.predict(test_X)
real_prediction17

array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0.])



---



In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.multiclass import OneVsRestClassifier
from sklearn.svm import LinearSVC

SVC_pipeline = Pipeline([('clf', OneVsRestClassifier(LinearSVC(), n_jobs=1))])

SVC_pipeline.fit(X_train, y_train)

Pipeline(memory=None,
         steps=[('clf',
                 OneVsRestClassifier(estimator=LinearSVC(C=1.0,
                                                         class_weight=None,
                                                         dual=True,
                                                         fit_intercept=True,
                                                         intercept_scaling=1,
                                                         loss='squared_hinge',
                                                         max_iter=1000,
                                                         multi_class='ovr',
                                                         penalty='l2',
                                                         random_state=None,
                                                         tol=0.0001,
                                                         verbose=0),
                                     n_jobs=1))],
         verbose=False)

In [ ]:
pipline_prediction = SVC_pipeline.predict(X_test)
print(accuracy_score(y_test, pipline_prediction))
print(classification_report(y_test, pipline_prediction))

0.5986842105263158
              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        61
         1.0       0.60      1.00      0.75        91

    accuracy                           0.60       152
   macro avg       0.30      0.50      0.37       152
weighted avg       0.36      0.60      0.45       152



In [ ]:
real_pipe_prediction = SVC_pipeline.predict(test_X)
real_pipe_prediction

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1.])



---



In [ ]:
# !pip install --upgrade autokeras
# !pip install --upgrade keras-tuner

     |████████████████████████████████| 174kB 12.8MB/s 
     |████████████████████████████████| 71kB 7.8MB/s 
  Created wheel for keras-tuner: filename=keras_tuner-1.0.2-cp36-none-any.whl size=78939 sha256=819269e0419711d717d0596cb77b8701ce71f0af49e2e119c6a756e34bd0e8bf
  Stored in directory: /root/.cache/pip/wheels/bb/a1/8a/7c3de0efb3707a1701b36ebbfdbc4e67aedf6d4943a1f463d6
  Created wheel for terminaltables: filename=terminaltables-3.1.0-cp36-none-any.whl size=15358 sha256=fd690ddc2f2f2030a4465e37e137d095f44cca2b5cc2e7f7cc8c87aa0c21f6d8
  Stored in directory: /root/.cache/pip/wheels/30/6b/50/6c75775b681fb36cdfac7f19799888ef9d8813aff9e379663e
Successfully built keras-tuner terminaltables
Requirement already up-to-date: keras-tuner in /usr/local/lib/python3.6/dist-packages (1.0.2)


In [ ]:
# import numpy as np
# import tensorflow as tf
# from tensorflow.keras.datasets import mnist
# from tensorflow.python.keras.utils.data_utils import Sequence
# import autokeras as ak

In [ ]:
# clf = ak.ImageClassifier(
#     overwrite=True,
#     max_trials=1)

# clf.fit(x_train, y_train, epochs=10)

# predicted_y = clf.predict(x_test)
# print(predicted_y)

# print(clf.evaluate(x_test, y_test))

ValueError: ignored