In [1]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.det(A)

6.66133814775094e-16

In [2]:
A = np.array([[1,1,0],[0,1,1],[1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [4]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [6]:
b = np.array([[2],[2],[3]])
b

array([[2],
       [2],
       [3]])

In [7]:
x = np.dot(Ainv, b)
x

array([[1.],
       [1.],
       [1.]])

In [8]:
np.dot(A, x) - b

array([[0.],
       [0.],
       [0.]])

In [9]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

array([[1.],
       [1.],
       [1.]])

In [13]:
from sklearn.datasets import load_boston

boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0,4,5,6]]
#범죄율, 공기 오염도, 방 개수, 오래된 정도 순
b = y[:4]
b

array([24. , 21.6, 34.7, 33.4])

In [15]:
Ainv = np.linalg.inv(A)
A

array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
       [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
       [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
       [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]])

In [16]:
x = np.dot(Ainv, b)

In [17]:
x #반비레, 반비례, 비례, 반비례

array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

In [19]:
A = np.array([[1,1,0],[0,1,1],[1,1,1],[1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [20]:
b = np.array([[2],[2],[3],[4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [24]:
Apinv = np.dot(np.linalg.inv(np.dot(A.T, A)), A.T)
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [25]:
x = np.dot(Apinv, b)

In [26]:
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [27]:
np.dot(A, x)

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [28]:
x, resid, rank, s = np.linalg.lstsq(A,b)

In [29]:
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [30]:
from sklearn.datasets import load_boston

boston = load_boston()
X = boston.data
y = boston.target

x, resid, rank, s = np.linalg.lstsq(X,y)
x

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

In [33]:
print(resid)
print(np.linalg.norm(np.dot(X,x)-y)**2)

[12228.04626104]
12228.046261044006
