스칼라(0D 텐서)

In [1]:
import numpy as np
x = np.array(12)

In [2]:
print(x)
x.ndim

12


0

벡터(1D 텐서)

In [3]:
x = np.array([12,3,6,14,7])

In [5]:
print(x)
x.ndim

[12  3  6 14  7]


1

행렬(2D 텐서)

In [6]:
x = np.array([[5,78,2,34,0],
             [6,79,3,35,1],
             [7,80,4,36,2]])

In [8]:
print(x)
x.ndim

[[ 5 78  2 34  0]
 [ 6 79  3 35  1]
 [ 7 80  4 36  2]]


2

3D 텐서와 고차원 텐서

In [10]:
x = np.array([[[5,78,2,34,0],
             [6,79,3,35,1],
             [7,80,4,36,2]],
            [[5,78,2,34,0],
             [6,79,3,35,1],
             [7,80,4,36,2]],
            [[5,78,2,34,0],
             [6,79,3,35,1],
             [7,80,4,36,2]]])

In [11]:
print(x)
x.ndim

[[[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]

 [[ 5 78  2 34  0]
  [ 6 79  3 35  1]
  [ 7 80  4 36  2]]]


3

In [12]:
from keras.datasets import mnist

(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

Using TensorFlow backend.
C:\Users\J\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\J\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\J\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
C:\Users\J\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [14]:
print(train_images.ndim, train_images.shape, train_images.dtype)

3 (60000, 28, 28) uint8


In [16]:
my_slice = train_images[10:100]
print(my_slice.shape)
my_slice = train_images[10:100,:,:]
print(my_slice.shape)
my_slice = train_images[10:100,0:28,0:28]
print(my_slice.shape)

(90, 28, 28)
(90, 28, 28)
(90, 28, 28)
