In [1]:
import numpy as np

x1 = np.array([1,2])
x2 = np.array([3,3])
x3 = np.array([10,14])

2 * x1 + x2 - 0.5 * x3

array([0., 0.])

In [2]:
X1 = np.array([[1,3], [2,4]])
np.linalg.matrix_rank(X1)

2

In [3]:
X2 = np.array([[1,3,5], [2,3,7]])
np.linalg.matrix_rank(X2)

2

In [4]:
X3 = np.array([1,1])
np.linalg.matrix_rank(X3)

1

In [5]:
x1 = np.array([[1],[1]])
x1

array([[1],
       [1]])

In [7]:
m1 = np.dot(x1,x1.T)
m1

array([[1, 1],
       [1, 1]])

In [8]:
np.linalg.matrix_rank(m1)

1

In [10]:
x1 = np.array([[1],[1]])
x2 = np.array([[1],[-1]])
h1 = np.dot(x1, x1.T)
h2 = np.dot(x2, x2.T)
h1, h2

(array([[1, 1],
        [1, 1]]), array([[ 1, -1],
        [-1,  1]]))

In [11]:
t1 = h1 + h2
t1

array([[2, 0],
       [0, 2]])

In [12]:
np.linalg.matrix_rank(t1)

2